// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: sim/devices.proto

package sim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeviceCreateRequest) Reset() {
	*x = DeviceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_devices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreateRequest) ProtoMessage() {}

func (x *DeviceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sim_devices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreateRequest.ProtoReflect.Descriptor instead.
func (*DeviceCreateRequest) Descriptor() ([]byte, []int) {
	return file_sim_devices_proto_rawDescGZIP(), []int{0}
}

type DeviceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeviceCreateResponse) Reset() {
	*x = DeviceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_devices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreateResponse) ProtoMessage() {}

func (x *DeviceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sim_devices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreateResponse.ProtoReflect.Descriptor instead.
func (*DeviceCreateResponse) Descriptor() ([]byte, []int) {
	return file_sim_devices_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceCreateResponse) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeviceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeviceDeleteRequest) Reset() {
	*x = DeviceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_devices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDeleteRequest) ProtoMessage() {}

func (x *DeviceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sim_devices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDeleteRequest.ProtoReflect.Descriptor instead.
func (*DeviceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sim_devices_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceDeleteRequest) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeviceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeviceDeleteResponse) Reset() {
	*x = DeviceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_devices_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDeleteResponse) ProtoMessage() {}

func (x *DeviceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sim_devices_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDeleteResponse.ProtoReflect.Descriptor instead.
func (*DeviceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_sim_devices_proto_rawDescGZIP(), []int{3}
}

var File_sim_devices_proto protoreflect.FileDescriptor

var file_sim_devices_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x69, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x7b, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x14, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6c, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sim_devices_proto_rawDescOnce sync.Once
	file_sim_devices_proto_rawDescData = file_sim_devices_proto_rawDesc
)

func file_sim_devices_proto_rawDescGZIP() []byte {
	file_sim_devices_proto_rawDescOnce.Do(func() {
		file_sim_devices_proto_rawDescData = protoimpl.X.CompressGZIP(file_sim_devices_proto_rawDescData)
	})
	return file_sim_devices_proto_rawDescData
}

var file_sim_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sim_devices_proto_goTypes = []interface{}{
	(*DeviceCreateRequest)(nil),  // 0: DeviceCreateRequest
	(*DeviceCreateResponse)(nil), // 1: DeviceCreateResponse
	(*DeviceDeleteRequest)(nil),  // 2: DeviceDeleteRequest
	(*DeviceDeleteResponse)(nil), // 3: DeviceDeleteResponse
}
var file_sim_devices_proto_depIdxs = []int32{
	0, // 0: Devices.Create:input_type -> DeviceCreateRequest
	2, // 1: Devices.Delete:input_type -> DeviceDeleteRequest
	1, // 2: Devices.Create:output_type -> DeviceCreateResponse
	3, // 3: Devices.Delete:output_type -> DeviceDeleteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sim_devices_proto_init() }
func file_sim_devices_proto_init() {
	if File_sim_devices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sim_devices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_devices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_devices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_devices_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sim_devices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sim_devices_proto_goTypes,
		DependencyIndexes: file_sim_devices_proto_depIdxs,
		MessageInfos:      file_sim_devices_proto_msgTypes,
	}.Build()
	File_sim_devices_proto = out.File
	file_sim_devices_proto_rawDesc = nil
	file_sim_devices_proto_goTypes = nil
	file_sim_devices_proto_depIdxs = nil
}
