// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: sim/platform.proto

package sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformClient interface {
	PrepareExtensionFunction(ctx context.Context, in *PlatformPrepareExtensionFunctionRequest, opts ...grpc.CallOption) (*PlatformPrepareExtensionFunctionResponse, error)
	ReleaseExtensionFunction(ctx context.Context, in *PlatformReleaseExtensionFunctionRequest, opts ...grpc.CallOption) (*PlatformReleaseExtensionFunctionResponse, error)
}

type platformClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformClient(cc grpc.ClientConnInterface) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) PrepareExtensionFunction(ctx context.Context, in *PlatformPrepareExtensionFunctionRequest, opts ...grpc.CallOption) (*PlatformPrepareExtensionFunctionResponse, error) {
	out := new(PlatformPrepareExtensionFunctionResponse)
	err := c.cc.Invoke(ctx, "/Platform/PrepareExtensionFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ReleaseExtensionFunction(ctx context.Context, in *PlatformReleaseExtensionFunctionRequest, opts ...grpc.CallOption) (*PlatformReleaseExtensionFunctionResponse, error) {
	out := new(PlatformReleaseExtensionFunctionResponse)
	err := c.cc.Invoke(ctx, "/Platform/ReleaseExtensionFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
// All implementations must embed UnimplementedPlatformServer
// for forward compatibility
type PlatformServer interface {
	PrepareExtensionFunction(context.Context, *PlatformPrepareExtensionFunctionRequest) (*PlatformPrepareExtensionFunctionResponse, error)
	ReleaseExtensionFunction(context.Context, *PlatformReleaseExtensionFunctionRequest) (*PlatformReleaseExtensionFunctionResponse, error)
	mustEmbedUnimplementedPlatformServer()
}

// UnimplementedPlatformServer must be embedded to have forward compatible implementations.
type UnimplementedPlatformServer struct {
}

func (UnimplementedPlatformServer) PrepareExtensionFunction(context.Context, *PlatformPrepareExtensionFunctionRequest) (*PlatformPrepareExtensionFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareExtensionFunction not implemented")
}
func (UnimplementedPlatformServer) ReleaseExtensionFunction(context.Context, *PlatformReleaseExtensionFunctionRequest) (*PlatformReleaseExtensionFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseExtensionFunction not implemented")
}
func (UnimplementedPlatformServer) mustEmbedUnimplementedPlatformServer() {}

// UnsafePlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServer will
// result in compilation errors.
type UnsafePlatformServer interface {
	mustEmbedUnimplementedPlatformServer()
}

func RegisterPlatformServer(s grpc.ServiceRegistrar, srv PlatformServer) {
	s.RegisterService(&Platform_ServiceDesc, srv)
}

func _Platform_PrepareExtensionFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformPrepareExtensionFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).PrepareExtensionFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Platform/PrepareExtensionFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).PrepareExtensionFunction(ctx, req.(*PlatformPrepareExtensionFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ReleaseExtensionFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformReleaseExtensionFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ReleaseExtensionFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Platform/ReleaseExtensionFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ReleaseExtensionFunction(ctx, req.(*PlatformReleaseExtensionFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Platform_ServiceDesc is the grpc.ServiceDesc for Platform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Platform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareExtensionFunction",
			Handler:    _Platform_PrepareExtensionFunction_Handler,
		},
		{
			MethodName: "ReleaseExtensionFunction",
			Handler:    _Platform_ReleaseExtensionFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sim/platform.proto",
}
